export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const GET_ADDITIONAL_LIST_REQUEST = 'GET_ADDITIONAL_LIST_REQUEST';
export const GET_ADDITIONAL_LIST_SUCCESS = 'GET_ADDITIONAL_LIST_SUCCESS';
export const GET_ADDITIONAL_LIST_FAILURE = 'GET_ADDITIONAL_LIST_FAILURE';
