export const GET_APPOINTMENTS_REQUEST = 'GET_APPOINTMENTS_REQUEST';
export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';
export const GET_APPOINTMENTS_FAILURE = 'GET_APPOINTMENTS_FAILURE';

export const CREATE_APPOINTMENT_REQUEST = 'CREATE_APPOINTMENT_REQUEST';
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAILURE = 'CREATE_APPOINTMENT_FAILURE';

export const UPDATE_APPOINTMENT_REQUEST = 'UPDATE_APPOINTMENT_REQUEST';
export const UPDATE_APPOINTMENT_SUCCESS = 'UPDATE_APPOINTMENT_SUCCESS';
export const UPDATE_APPOINTMENT_FAILURE = 'UPDATE_APPOINTMENT_FAILURE';

export const REMOVE_APPOINTMENT_REQUEST = 'REMOVE_APPOINTMENT_REQUEST';
export const REMOVE_APPOINTMENT_SUCCESS = 'REMOVE_APPOINTMENT_SUCCESS';
export const REMOVE_APPOINTMENT_FAILURE = 'REMOVE_APPOINTMENT_FAILURE';

export const REQUEST_REFUND_APPOINTMENT_REQUEST = 'REQUEST_REFUND_APPOINTMENT_REQUEST';
export const REQUEST_REFUND_APPOINTMENT_SUCCESS = 'REQUEST_REFUND_APPOINTMENT_SUCCESS';
export const REQUEST_REFUND_APPOINTMENT_FAILURE = 'REQUEST_REFUND_APPOINTMENT_FAILURE';
